export default {
	defaultLanguageKeys: {
		"back": "Назад",
		"dismissalPageTitle": "Завершення співпраці",
		"finishDismissalButton": "Завершити",
		"employeeFiredAlert": "Працівника звільнено",
		"errorWhileAssignmentAlert": "Помилка при оновленні інформації про звільнення працівника: ",
		"dismissalFormTitle": "Інформація про звільнення", 
		"dismissalInfoTitle": "Планування дати звільнення", 
		"dismissalInfoDescription": "Щоб вчасно оформити всі документи - вкажіть дату звільнення не раніше ніж за 7-14 календарних днів до останнього робочого дня працівника.", 
		"endDatePickerLabel": "Дата завершення роботи", 
		"dismissalReasonSelectLabel": "Причина звільнення", 
		"dismissalReasonSelectPlaceholder": "Емоційне вигорання",
		"dismissalReasonSelectOptionHealth": "Стан здоров'я",
		"dismissalReasonSelectOptionAbroad": "Переїзд за кордон",
		"dismissalReasonSelectOptionOtherCity": "Переїзд в інше місто",
		"dismissalReasonSelectOptionPhysicalLoad": "Завелике фізичне навантаження",
		"dismissalReasonSelectOptionMobilization": "Мобілізація",
		"dismissalReasonSelectOptionProfession": "Робота по спеціальності",
		"dismissalReasonSelectOptionEducation": "Навчання/сесія",
		"dismissalReasonSelectOptionBurnout": "Емоційне вигорання",
		"dismissalReasonSelectOptionSchedule": "Графік роботи",
		"dismissalReasonSelectOptionSalary": "Оплата",
		"dismissalReasonSelectOptionLocation": "Локація",
		"dismissalReasonSelectOptionNewCompany": "Робота в іншій компанії",
		"dismissalReasonSelectOptionBlackList": "Зловживання (чорний список)",
		"dismissalReasonSelectOptionThirdWarning": "3-є попередження",
		"dismissalReasonSelectOptionOther": "Інша причина",
		"otherReasonInputPlaceholder": "Введіть іншу причину",
		"responsiblePersonSelectLabel": "Відповідальний за звільнення",
		"responsiblePersonSelectPlaceholder": "Тарас Шевченко",
	},

	enLanguageKeys: {
		"back": "Back",
		"dismissalPageTitle": "End of cooperation",
		"finishDismissalButton": "Complete",
		"employeeFiredAlert": "Employee has been dismissed",
		"errorWhileAssignmentAlert": "Error updating employee: ",
		"dismissalFormTitle": "Dismissal Information", 
		"dismissalInfoTitle": "Scheduling the termination date", 
		"dismissalInfoDescription": "To ensure timely processing of all documents, please specify the termination date no earlier than 7-14 calendar days before the employee's last working day.", 
		"endDatePickerLabel": "End Date", 
		"dismissalReasonSelectLabel": "Reason for Dismissal", 
		"dismissalReasonSelectPlaceholder": "Burnout",
		"dismissalReasonSelectOptionHealth": "Health status",
		"dismissalReasonSelectOptionAbroad": "Relocating abroad",
		"dismissalReasonSelectOptionOtherCity": "Relocating to another city",
		"dismissalReasonSelectOptionPhysicalLoad": "Too much physical activity/workload",
		"dismissalReasonSelectOptionMobilization": "Mobilization",
		"dismissalReasonSelectOptionProfession": "Specialty-related work",
		"dismissalReasonSelectOptionEducation": "Study / Exam Session",
		"dismissalReasonSelectOptionBurnout": "Burnout",
		"dismissalReasonSelectOptionSchedule": "Work schedule",
		"dismissalReasonSelectOptionSalary": "Salary",
		"dismissalReasonSelectOptionLocation": "Location",
		"dismissalReasonSelectOptionNewCompany": "Work at another company",
		"dismissalReasonSelectOptionBlackList": "Misconduct (black list)",
		"dismissalReasonSelectOptionThirdWarning": "Third warning",
		"dismissalReasonSelectOptionOther": "Another reason",
		"otherReasonInputPlaceholder": "Enter another reason",
		"responsiblePersonSelectLabel": "Responsible for dismissals",
		"responsiblePersonSelectPlaceholder": "Taras Shevchenko",
	}
}