export default {
	defaultLanguageKeys: {
		"back": "Назад",
		"addUserPageTitle": "Новий працівник",
		"editUserInfoPageTitle": "Редагувати дані працівника",
		"editUserInfoButton": "Зберегти",
		"addUserButton": "Створити профіль",
		"editUserFormTitle": "Основна інформація",
		"userNameInputLabel": "Ім'я",
		"userNameInputPlaceholder": "Тарас",
		"userNameInputError": "Введіть коректне ім'я",
		"userSurnameInputLabel": "Прізвище",
		"userSurnameInputPlaceholder": "Шевченко",
		"userSurnameInputError": "Введіть прізвище",
		"userMiddlenameInputLabel": "По батькові",
		"userMiddlenameInputPlaceholder": "Григорович",
		"userMiddlenameInputError": "Введіть по батькові",
		"userPhoneInputLabel": "Номер телефону",
		"userPhoneInputPlaceholder": "+380 00 000 00 00",
		"userPhoneInputError": "Некоректний формат номеру",
		"userEmailInputLabel": "Пошта",
		"userEmailInputPlaceholder": "example@gmail.com",
		"userEmailInputError": "Некоректна пошта",
		"userSexSelectLabel": "Стать",
		"userSexSelectOptionMale": "Чоловіча",
		"userSexSelectOptionFemale": "Жіноча",
		"userSexSelectPlaceholder": "Чоловіча",
		"userSexSelectError": "Стать",
		"userBirthPickerLabel": "Дата народження",
	},

	enLanguageKeys: {
		"back": "Back",
		"addUserPageTitle": "New employee",
		"editUserInfoPageTitle": "Edit info about employee",
		"editUserInfoButton": "Save",
		"addUserButton": "Create profile",
		"editUserFormTitle": "Main information",
		"userNameInputLabel": "Name",
		"userNameInputPlaceholder": "Taras",
		"userNameInputError": "Enter a valid name",
		"userSurnameInputLabel": "Surname",
		"userSurnameInputPlaceholder": "Shevchenko",
		"userSurnameInputError": "Enter surname",
		"userMiddlenameInputLabel": "Middle name",
		"userMiddlenameInputPlaceholder": "Grygorovych",
		"userMiddlenameInputError": "Enter middle name",
		"userPhoneInputLabel": "Phone Number",
		"userPhoneInputPlaceholder": "+380 00 000 00 00",
		"userPhoneInputError": "Invalid format",
		"userEmailInputLabel": "E-mail",
		"userEmailInputPlaceholder": "example@gmail.com",
		"userEmailInputError": "Invalid format",
		"userSexSelectLabel": "Gender",
		"userSexSelectOptionMale": "Male",
		"userSexSelectOptionFemale": "Female",
		"userSexSelectPlaceholder": "Male",
		"userSexSelectError": "Gender",
		"userBirthPickerLabel": "Date of birth",
	}
}